Update Dockerfile to use the ADD command
AlbrechtL/openwrt-docker pull request #2
Opened 2024-05-20 11:24 UTC by TRex22

# What does this PR do?
Im not sure why but the first two wget commands kept failing for me. Using `ADD` resolved the issue.

2024-05-29 15:25 UTC, AlbrechtL requested changes
Thanks for the improvements. I also don't know why your `wget` failed. Maybe `wget` is running inside the alpine and not at the host - but this is just guessing.

I added a comment inside your change.

2024-05-29 15:25 UTC, AlbrechtL commented on Dockerfile
> +ADD https://github.com/bugy/script-server/releases/download/1.18.0/script-server.zip /tmp/noVNC-${NOVNC_VERSION}/script-server.zip
It doesn't make sense to put script-server.zip into the noVNC folder. Can you change that, please?

In the original code it doesn't make sense either.

2024-10-02 21:32 UTC, AlbrechtL commented
Closed because of no activity.

2024-10-02 21:32 UTC, closed without merging

2024-11-24 09:59 UTC, TRex22 commented
Sorry @AlbrechtL been a busy year and I lost track of stuff...
Im busy trying to add a few things here and will open some PRs and do your feedback when Im ready to